# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"
plugins:
  - jekyll-include-cache

# Site Settings
locale: "en-CA"
rtl: false
title: "Arya's Coding Lab"
title_separator: "-"
subtitle:
name: "Arya"
description: "An amazing website."
url:
baseurl:
repository: "microbitcoder652/microbitcoder652.github.io"
teaser:
logo:
masthead_title:
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: true
copyright:
copyright_url:

# Comments
comments:
  provider: false

# reCaptcha
reCaptcha:
  siteKey:
  secret:

# Atom Feed
atom_feed:
  path:
  hide: false

# Search
search: true
search_full_content: false
search_provider: lunr
lunr:
  search_within_pages: false

social:
  type: Person
  name: Arya
  links:
    - "https://github.com/microbitcoder652/microbit-v2-micro-chat"
    - "https://github.com/microbitcoder652/microbit-flappy-bird"
    - "https://github.com/microbitcoder652/microbit-v2-outdoor-kit"


# Analytics
analytics:
  provider: false

# Site Author
author:
  name: "Arya"
  bio: "I am an **amazing** person."
  location: "Toronto, ON"
  email: "arya.sharma2421@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:arya.sharma2421@gmail.com"

