theme                  : "null"
minimal_mistakes_skin    : "catppuccin_mocha"

locale                   : "en-CA"
direction                : "ltr"
title                    : "Arya's Coding World"
title_separator          : "-"
name                     : "Arya Sharma"
description              : "Welcome to my personal website, built with Jekyll and the Minimal Mistakes theme. This site is a hub for my micro:bit projects, coding experiments, and creative tech adventures."
url                      : "https://microbitcoder652.github.io"
repository               : "microbitcoder652/microbitcoder652.github.io"
words_per_minute         : 200
enable_copy_code_button  : true

comments:
  provider               : "giscus"
  
  giscus:
    repo_id              : R_kgDOSG7Vwg
    category_name        : "Announcements"
    category_id          : DIC_kwDOSG7Vws4DEWKO
    discussion_term      : pathname
    reactions_enabled    : 1
    theme                : catppuccin_mocha
    strict               : 1
    input_position       : bottom
    emit_metadata        : 0
    lang                 : en
    lazy                 : true
  
atom_feed:
  path                   : feed.xml
  hide                   : false

google_site_verification : "MAWwgasCw3Iml0Db8EuyKc6cow_bU-wwvLxVtReG9fU"
bing_site_verification   : "1E8140AF75C7076B73F616579B8B2D76"

social:
  type: Person
  name: "Arya Sharma"
  links:
    - "https://github.com/microbitcoder652"

author:
  name             : "Arya Sharma"
  bio              : "I love coding and playing games"
  location         : "Scarborough, ON"
  email            : "arya.sharma2421@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:arya.sharma2421@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/microbitcoder652"
      
footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:arya.sharma2421@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/microbitcoder652"
  since: "2022"

include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - LICENSE
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

sass:
  sass_dir: _sass
  style: compressed 
  quiet_deps: true
  silence_deprecations: ['import']

permalink: /:categories/:title/
timezone: America/Toronto

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
