# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"

# Site Settings
locale: "en-CA"
rtl: false
title: "Site Title"
title_separator: "-"
subtitle:
name: "Arya"
description: "An amazing website."
url:
baseurl:
repository: "arya/repo-1"  # ← Replace with your actual repo
teaser:
logo:
masthead_title:
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: true
copyright:
copyright_url:

# Comments
comments:
  provider: false

# reCaptcha
reCaptcha:
  siteKey:
  secret:

# Atom Feed
atom_feed:
  path:
  hide: false

# Search
search: true
search_full_content: false
search_provider: lunr
lunr:
  search_within_pages: false

# Social Sharing
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:

# Social Profiles
social:
  type: Person
  name: Arya
  links:
    - "https://github.com/arya/repo-2"  # ← Replace with your second repo
    - "https://github.com/arya/repo-3"  # ← Replace with your third repo

# Analytics
analytics:
  provider: false

# Site Author
author:
  name: "Arya"
  avatar:
  bio: "I am an **amazing** person."
  location: "Calgary, AB"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url:

